version: '3'

services:
  node-build-monitor:
    restart: unless-stopped
    image: marcells/node-build-monitor
    build: .
    links:
      - tfs-proxy
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
  
  tfs-proxy:
    restart: unless-stopped
    image: marcells/tfs-proxy
    container_name: tfs-proxy
    build: .